#!/usr/bin/env node
/**
 * generate-report.mjs - Create standup report from collected artifacts
 * Usage: node generate-report.mjs --github-data <json> --memory-data <json>
 */

// Parse args
const args = Object.fromEntries(process.argv.slice(2).map(a => {
  const [k, v] = a.replace('--', '').split('=');
  return [k, v || ''];
}));

function formatDate(date = new Date()) {
  return date.toISOString().split('T')[0];
}

function generateReport(artifacts, memory) {
  const today = formatDate();
  const lines = [
    `# Daily Standup — ${today}`,
    '',
    '## Yesterday\'s Accomplishments',
    ''
  ];
  
  // GitHub activity
  if (artifacts.github?.repositories) {
    let hasActivity = false;
    for (const repo of artifacts.github.repositories) {
      if (repo.error) continue;
      if (repo.commits?.length || repo.prsOpened || repo.prsMerged || repo.issuesClosed) {
        hasActivity = true;
        lines.push(`**${repo.repo}:**`);
        if (repo.commits?.length) {
          lines.push(`- Commits: ${repo.commits.length}`);
          for (const c of repo.commits.slice(0, 3)) {
            lines.push(`  - \`${c.sha}\` ${c.message}`);
          }
        }
        if (repo.prsOpened) lines.push(`- Opened ${repo.prsOpened} PR(s)`);
        if (repo.prsMerged) lines.push(`- Merged ${repo.prsMerged} PR(s)`);
        if (repo.issuesClosed) lines.push(`- Closed ${repo.issuesClosed} issue(s)`);
        lines.push('');
      }
    }
    if (!hasActivity) {
      lines.push('- No GitHub activity recorded');
      lines.push('');
    }
  }
  
  // Slack activity placeholder
  if (artifacts.slack) {
    lines.push('**Communication:**');
    lines.push(`- ${artifacts.slack.messageCount || 'Several'} Slack messages`);
    lines.push('');
  }
  
  // Today's priorities (carry over from yesterday if exists)
  lines.push('## Today\'s Priorities');
  lines.push('');
  if (memory?.priorities?.length) {
    for (const p of memory.priorities) {
      lines.push(`- [ ] ${p}`);
    }
  } else {
    lines.push('- [ ] Review priorities and plan work');
  }
  lines.push('');
  
  // Blockers
  lines.push('## Blockers');
  lines.push('');
  if (memory?.blockers?.length) {
    for (const b of memory.blockers) {
      lines.push(`- 🚧 ${b}`);
    }
  } else {
    lines.push('- None reported');
  }
  lines.push('');
  
  // Learnings
  if (memory?.learnings?.length) {
    lines.push('## Learnings / Notes');
    lines.push('');
    for (const l of memory.learnings) {
      lines.push(`- 💡 ${l}`);
    }
    lines.push('');
  }
  
  lines.push('---');
  lines.push('*Generated by daily-standup-agent*');
  
  return lines.join('\n');
}

// Main
async function main() {
  const artifacts = {
    github: args.githubData ? JSON.parse(args.githubData) : null,
    slack: args.slackData ? JSON.parse(args.slackData) : null
  };
  
  const memory = args.memoryData ? JSON.parse(args.memoryData) : {};
  
  const report = generateReport(artifacts, memory);
  console.log(report);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
