#!/usr/bin/env node
/**
 * Daily Brief Agent — Main Entry Point
 * Aggregates calendar, email, news, and tasks into a morning brief
 */

import { readFileSync, existsSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

const CONFIG_PATH = join(homedir(), '.openclaw', 'skills', 'daily-brief-agent', 'config.json');

// Default configuration
const DEFAULTS = {
  schedule: '0 8 * * 1-5',
  timezone: 'America/New_York',
  sources: {
    calendar: { enabled: false },
    email: { enabled: false },
    news: { enabled: true, feeds: ['https://hnrss.org/frontpage'], max_items: 5 },
    tasks: { enabled: false }
  },
  delivery: { channel: 'console', format: 'markdown' },
  ai: { model: 'claude-3-5-sonnet', style: 'concise_bullets' }
};

async function loadConfig() {
  if (!existsSync(CONFIG_PATH)) {
    console.log('⚠️  No config found. Using defaults.');
    console.log(`Create config at: ${CONFIG_PATH}`);
    return DEFAULTS;
  }
  
  try {
    const raw = readFileSync(CONFIG_PATH, 'utf-8');
    return { ...DEFAULTS, ...JSON.parse(raw) };
  } catch (err) {
    console.error('Config parse error:', err.message);
    return DEFAULTS;
  }
}

async function fetchNews(config) {
  if (!config.sources.news.enabled) return null;
  
  const { feeds, max_items } = config.sources.news;
  const items = [];
  
  for (const feed of feeds.slice(0, 2)) {
    try {
      const response = await fetch(feed, {
        headers: { 'User-Agent': 'DailyBriefAgent/1.0' }
      });
      const xml = await response.text();
      
      // Simple RSS parsing
      const titles = xml.match(/<title>([^<]+)<\/title>/g) || [];
      const links = xml.match(/<link>([^<]+)<\/link>/g) || [];
      
      for (let i = 1; i < Math.min(titles.length, max_items + 1); i++) {
        const title = titles[i]?.replace(/<\/?title>/g, '');
        const link = links[i]?.replace(/<\/?link>/g, '');
        if (title && title.length > 10) {
          items.push({ title: title.trim(), url: link?.trim() || '#' });
        }
      }
    } catch (err) {
      console.log(`  ⚠️  Failed to fetch ${feed}: ${err.message}`);
    }
  }
  
  return { section: '📰 News', items: items.slice(0, max_items) };
}

async function generateMockBrief(config) {
  const date = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', 
    month: 'long', 
    day: 'numeric' 
  });
  
  const news = await fetchNews(config);
  
  let brief = `## 📅 Daily Brief — ${date}\n\n`;
  
  // Calendar section
  if (config.sources.calendar.enabled) {
    brief += `### Today's Calendar\n`;
    brief += `- Configure Google Calendar to see your meetings\n`;
    brief += `- Set GOOGLE_CALENDAR_CREDENTIALS_PATH in your environment\n\n`;
  }
  
  // News section
  if (news && news.items.length > 0) {
    brief += `### ${news.section}\n`;
    for (const item of news.items.slice(0, 5)) {
      brief += `- ${item.title}\n`;
    }
    brief += `\n`;
  }
  
  // Action items placeholder
  brief += `### ✅ Action Items\n`;
  brief += `- [ ] Configure your daily brief sources\n`;
  brief += `- [ ] Set up delivery channel (Slack/email)\n`;
  brief += `- [ ] Customize AI style preferences\n\n`;
  
  // AI insight
  brief += `### 🤖 AI Insight\n`;
  brief += `*Your brief is configured! Enable more sources in your config.json for richer insights.*\n\n`;
  brief += `---\n*Generated by Daily Brief Agent*\n`;
  
  return brief;
}

async function deliver(brief, config) {
  const { channel } = config.delivery;
  
  if (channel === 'console') {
    console.log('\n' + '='.repeat(60));
    console.log(brief);
    console.log('='.repeat(60) + '\n');
  } else if (channel === 'slack') {
    const webhook = process.env.SLACK_WEBHOOK_URL;
    if (!webhook) {
      console.log('⚠️  SLACK_WEBHOOK_URL not set. Outputting to console:');
      console.log(brief);
      return;
    }
    
    try {
      await fetch(webhook, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: brief })
      });
      console.log('✅ Brief delivered to Slack');
    } catch (err) {
      console.error('Failed to send to Slack:', err.message);
    }
  }
}

async function main() {
  console.log('📰 Daily Brief Agent — Starting...\n');
  
  const config = await loadConfig();
  const brief = await generateMockBrief(config);
  await deliver(brief, config);
  
  console.log('✅ Daily brief complete');
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
