#!/usr/bin/env node
/**
 * Agent Cost Tracker — Report Generator
 * 
 * Generates daily/weekly cost reports from the SQLite database.
 * Usage: node report.js [--period daily|weekly] [--output markdown|slack|discord]
 */

import { Database } from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import https from 'https';

const DB_DIR = process.env.COST_REPORT_DIR || './workspace/cost-reports';
const DB_PATH = path.join(DB_DIR, 'agent-cost-tracker.db');

function getDb() {
  if (!fs.existsSync(DB_DIR)) {
    fs.mkdirSync(DB_DIR, { recursive: true });
  }
  return new Database(DB_PATH);
}

function initDb() {
  const db = getDb();
  db.exec(`
    CREATE TABLE IF NOT EXISTS runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
      session_key TEXT,
      model TEXT,
      input_tokens INTEGER DEFAULT 0,
      output_tokens INTEGER DEFAULT 0,
      cost REAL DEFAULT 0,
      skills_used TEXT,
      subagents_spawned INTEGER DEFAULT 0,
      subagents_completed INTEGER DEFAULT 0,
      duration_ms INTEGER,
      status TEXT DEFAULT 'success'
    );
    CREATE INDEX IF NOT EXISTS idx_timestamp ON runs(timestamp);
    CREATE INDEX IF NOT EXISTS idx_model ON runs(model);
  `);
  return db;
}

function getDailyStats(date) {
  const db = getDb();
  const startOfDay = `${date} 00:00:00`;
  const endOfDay = `${date} 23:59:59`;
  
  const stats = db.prepare(`
    SELECT 
      COUNT(*) as total_runs,
      SUM(input_tokens) as total_input,
      SUM(output_tokens) as total_output,
      SUM(cost) as total_cost,
      SUM(subagents_spawned) as total_subagents,
      model,
      COUNT(DISTINCT model) as model_count
    FROM runs 
    WHERE timestamp BETWEEN ? AND ?
    GROUP BY model
  `).all(startOfDay, endOfDay);
  
  return stats;
}

function generateMarkdownReport(period, date) {
  const stats = getDailyStats(date);
  
  if (stats.length === 0) {
    return `# Agent Cost Report — ${date}\n\nNo agent runs recorded for this period.`;
  }
  
  const totalRuns = stats.reduce((sum, s) => sum + s.total_runs, 0);
  const totalInput = stats.reduce((sum, s) => sum + s.total_input, 0);
  const totalOutput = stats.reduce((sum, s) => sum + s.total_output, 0);
  const totalCost = stats.reduce((sum, s) => sum + s.total_cost, 0);
  const totalSubagents = stats.reduce((sum, s) => sum + s.total_subagents, 0);
  
  return `# Agent Cost Report — ${date}

## Summary
- **Total Runs**: ${totalRuns}
- **Total Cost**: $${totalCost.toFixed(2)}
- **Total Input Tokens**: ${totalInput.toLocaleString()}
- **Total Output Tokens**: ${totalOutput.toLocaleString()}
- **Subagents Spawned**: ${totalSubagents}

## By Model
| Model | Runs | Input Tokens | Output Tokens | Cost |
|-------|------|--------------|---------------|------|
${stats.map(s => `| ${s.model} | ${s.total_runs} | ${s.total_input.toLocaleString()} | ${s.total_output.toLocaleString()} | $${s.total_cost.toFixed(2)} |`).join('\n')}

---
*Generated by agent-cost-tracker skill*
`;
}

function generateSlackPayload(period, date) {
  const stats = getDailyStats(date);
  
  if (stats.length === 0) {
    return { text: `📊 No agent runs recorded for ${date}` };
  }
  
  const totalRuns = stats.reduce((sum, s) => sum + s.total_runs, 0);
  const totalCost = stats.reduce((sum, s) => sum + s.total_cost, 0);
  const totalSubagents = stats.reduce((sum, s) => sum + s.total_subagents, 0);
  
  return {
    text: `📊 Daily Agent Report — ${date}`,
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `📊 Agent Cost Report — ${date}`
        }
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Total Runs:*\n${totalRuns}` },
          { type: "mrkdwn", text: `*Total Cost:*\n$${totalCost.toFixed(2)}` },
          { type: "mrkdwn", text: `*Subagents:*\n${totalSubagents}` },
          { type: "mrkdwn", text: `*Models Used:*\n${stats.length}` }
        ]
      }
    ]
  };
}

async function postToSlack(payload) {
  const webhook = process.env.SLACK_WEBHOOK_URL;
  if (!webhook) {
    console.error('SLACK_WEBHOOK_URL not set');
    return;
  }
  
  return new Promise((resolve, reject) => {
    const url = new URL(webhook);
    const data = JSON.stringify(payload);
    
    const req = https.request({
      hostname: url.hostname,
      path: url.pathname,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': data.length
      }
    }, (res) => {
      res.on('data', () => {});
      res.on('end', resolve);
    });
    
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

async function main() {
  const args = process.argv.slice(2);
  const period = args.includes('--period') ? args[args.indexOf('--period') + 1] : 'daily';
  const output = args.includes('--output') ? args[args.indexOf('--output') + 1] : 'markdown';
  
  const today = new Date().toISOString().split('T')[0];
  
  initDb();
  
  if (output === 'slack') {
    const payload = generateSlackPayload(period, today);
    await postToSlack(payload);
    console.log('Report posted to Slack');
  } else {
    const report = generateMarkdownReport(period, today);
    const filename = path.join(DB_DIR, `${period}-${today}.md`);
    fs.writeFileSync(filename, report);
    console.log(`Report saved to ${filename}`);
  }
}

main().catch(console.error);
